// Copyright (C) 2025 by Haguk Kim

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "Sound/SoundCue.h"
#include "AudioConfig.generated.h"

UENUM(BlueprintType)
enum class EGunshotAudioReference : uint8
{
	EGR_NULL,
	
	// Gunshots
	EGR_MACHINEGUN_A_1,
	EGR_MACHINEGUN_A_2,
	EGR_MACHINEGUN_A_3,
	EGR_MACHINEGUN_A_4,
	EGR_MACHINEGUN_A_5,
	EGR_MACHINEGUN_A_6,
	EGR_MACHINEGUN_A_7,
	EGR_MACHINEGUN_A_8,

	EGR_MACHINEGUN_B_1,
	EGR_MACHINEGUN_B_2,
	EGR_MACHINEGUN_B_3,
	EGR_MACHINEGUN_B_4,
	EGR_MACHINEGUN_B_5,
	EGR_MACHINEGUN_B_6,
	EGR_MACHINEGUN_B_7,
	EGR_MACHINEGUN_B_8,

	EGR_MACHINEGUN_C_1,
	EGR_MACHINEGUN_C_2,
	EGR_MACHINEGUN_C_3,
	EGR_MACHINEGUN_C_4,
	EGR_MACHINEGUN_C_5,
	EGR_MACHINEGUN_C_6,
	EGR_MACHINEGUN_C_7,
	EGR_MACHINEGUN_C_8,

	EGR_PISTOL_A_1,
	EGR_PISTOL_A_2,
	EGR_PISTOL_A_3,
	EGR_PISTOL_A_4,
	EGR_PISTOL_A_5,
	EGR_PISTOL_A_6,
	EGR_PISTOL_A_7,
	EGR_PISTOL_A_8,

	EGR_PISTOL_B_1,
	EGR_PISTOL_B_2,
	EGR_PISTOL_B_3,
	EGR_PISTOL_B_4,
	EGR_PISTOL_B_5,
	EGR_PISTOL_B_6,
	EGR_PISTOL_B_7,
	EGR_PISTOL_B_8,

	EGR_HANDGUN_A_1,
	EGR_HANDGUN_A_2,
	EGR_HANDGUN_A_3,
	EGR_HANDGUN_A_4,
	EGR_HANDGUN_A_5,
	EGR_HANDGUN_A_6,
	EGR_HANDGUN_A_7,
	EGR_HANDGUN_A_8,

	EGR_HANDGUN_B_1,
	EGR_HANDGUN_B_2,
	EGR_HANDGUN_B_3,
	EGR_HANDGUN_B_4,
	EGR_HANDGUN_B_5,
	EGR_HANDGUN_B_6,
	EGR_HANDGUN_B_7,
	EGR_HANDGUN_B_8,

	EGR_RIFLE_A_1,
	EGR_RIFLE_A_2,
	EGR_RIFLE_A_3,
	EGR_RIFLE_A_4,
	EGR_RIFLE_A_5,
	EGR_RIFLE_A_6,
	EGR_RIFLE_A_7,
	EGR_RIFLE_A_8,

	EGR_RIFLE_B_1,
	EGR_RIFLE_B_2,
	EGR_RIFLE_B_3,
	EGR_RIFLE_B_4,
	EGR_RIFLE_B_5,
	EGR_RIFLE_B_6,
	EGR_RIFLE_B_7,
	EGR_RIFLE_B_8,

	EGR_RIFLE_C_1,
	EGR_RIFLE_C_2,
	EGR_RIFLE_C_3,
	EGR_RIFLE_C_4,
	EGR_RIFLE_C_5,
	EGR_RIFLE_C_6,
	EGR_RIFLE_C_7,
	EGR_RIFLE_C_8,

	EGR_RIFLE_D_1,
	EGR_RIFLE_D_2,
	EGR_RIFLE_D_3,
	EGR_RIFLE_D_4,
	EGR_RIFLE_D_5,
	EGR_RIFLE_D_6,
	EGR_RIFLE_D_7,
	EGR_RIFLE_D_8,

	EGR_RIFLE_E_1,
	EGR_RIFLE_E_2,
	EGR_RIFLE_E_3,
	EGR_RIFLE_E_4,
	EGR_RIFLE_E_5,
	EGR_RIFLE_E_6,
	EGR_RIFLE_E_7,
	EGR_RIFLE_E_8,

	EGR_SHOTGUN_A_1,
	EGR_SHOTGUN_A_2,
	EGR_SHOTGUN_A_3,
	EGR_SHOTGUN_A_4,
	EGR_SHOTGUN_A_5,
	EGR_SHOTGUN_A_6,
	EGR_SHOTGUN_A_7,
	EGR_SHOTGUN_A_8,

	EGR_SHOTGUN_B_1,
	EGR_SHOTGUN_B_2,
	EGR_SHOTGUN_B_3,
	EGR_SHOTGUN_B_4,
	EGR_SHOTGUN_B_5,
	EGR_SHOTGUN_B_6,
	EGR_SHOTGUN_B_7,
	EGR_SHOTGUN_B_8,

	EGR_SHOTGUN_C_1,
	EGR_SHOTGUN_C_2,
	EGR_SHOTGUN_C_3,
	EGR_SHOTGUN_C_4,
	EGR_SHOTGUN_C_5,
	EGR_SHOTGUN_C_6,
	EGR_SHOTGUN_C_7,
	EGR_SHOTGUN_C_8,

	EGR_SNIPER_A_1,
	EGR_SNIPER_A_2,
	EGR_SNIPER_A_3,
	EGR_SNIPER_A_4,
	EGR_SNIPER_A_5,
	EGR_SNIPER_A_6,
	EGR_SNIPER_A_7,
	EGR_SNIPER_A_8,

	EGR_ASSAULT_A_1,
	EGR_ASSAULT_A_2,
	EGR_ASSAULT_A_3,
	EGR_ASSAULT_A_4,
	EGR_ASSAULT_A_5,
	EGR_ASSAULT_A_6,
	EGR_ASSAULT_A_7,
	EGR_ASSAULT_A_8,

	EGR_ASSAULT_B_1,
	EGR_ASSAULT_B_2,
	EGR_ASSAULT_B_3,
	EGR_ASSAULT_B_4,
	EGR_ASSAULT_B_5,
	EGR_ASSAULT_B_6,
	EGR_ASSAULT_B_7,
	EGR_ASSAULT_B_8,

	EGR_ASSAULT_C_1,
	EGR_ASSAULT_C_2,
	EGR_ASSAULT_C_3,
	EGR_ASSAULT_C_4,
	EGR_ASSAULT_C_5,
	EGR_ASSAULT_C_6,
	EGR_ASSAULT_C_7,
	EGR_ASSAULT_C_8,

	EGR_REVOLVER_A_1,
	EGR_REVOLVER_A_2,
	EGR_REVOLVER_A_3,
	EGR_REVOLVER_A_4,
	EGR_REVOLVER_A_5,
	EGR_REVOLVER_A_6,
	EGR_REVOLVER_A_7,
	EGR_REVOLVER_A_8,

	EGR_REVOLVER_B_1,
	EGR_REVOLVER_B_2,
	EGR_REVOLVER_B_3,
	EGR_REVOLVER_B_4,
	EGR_REVOLVER_B_5,
	EGR_REVOLVER_B_6,
	EGR_REVOLVER_B_7,
	EGR_REVOLVER_B_8,

	EGR_SMG_A_1,
	EGR_SMG_A_2,
	EGR_SMG_A_3,
	EGR_SMG_A_4,
	EGR_SMG_A_5,
	EGR_SMG_A_6,
	EGR_SMG_A_7,
	EGR_SMG_A_8,

	EGR_SMG_B_1,
	EGR_SMG_B_2,
	EGR_SMG_B_3,
	EGR_SMG_B_4,
	EGR_SMG_B_5,
	EGR_SMG_B_6,
	EGR_SMG_B_7,
	EGR_SMG_B_8,

	EGR_MINIGUN_A_1,
	EGR_MINIGUN_A_2,
	EGR_MINIGUN_A_3,
	EGR_MINIGUN_A_4,
	EGR_MINIGUN_A_5,
	EGR_MINIGUN_A_6,
	EGR_MINIGUN_A_7,
	EGR_MINIGUN_A_8,

	EGR_ANTITANK_A_1,
	EGR_ANTITANK_A_2,
	EGR_ANTITANK_A_3,
	EGR_ANTITANK_A_4,
	EGR_ANTITANK_A_5,
	EGR_ANTITANK_A_6,
	EGR_ANTITANK_A_7,
	EGR_ANTITANK_A_8,
};

UENUM(BlueprintType)
enum class EGunMiscAudioReference : uint8
{
	EGM_NULL,

	// Empty ammo
	EGM_AMMOEMPTY_1,
	EGM_AMMOEMPTY_2,
	EGM_AMMOEMPTY_3,
	EGM_AMMOEMPTY_4,
	EGM_AMMOEMPTY_5,
	EGM_AMMOEMPTY_6,
};

/**
 * 
 */
UCLASS()
class PROJECTTR_API UAudioConfig : public UDataAsset
{
	GENERATED_BODY()
	
public:
	// 네임태그 기반 에셋 서칭
	// NOTE: 
	// GunItem의 GPC 레플리케이션과, 해당 GPC가 사용할 SFX 간의 의존관계를 없애고자 Enum을 사용해 사용할 SFX에 대한 정보를 저장함
	USoundCue* SearchAudioFromEnum(EGunshotAudioReference AudioRef) const;
	USoundCue* SearchAudioFromEnum(EGunMiscAudioReference AudioRef) const;

/* Gun SFXs */
/* Gunshots */
public:
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	USoundCue* MachineGun_A_Fire_1;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	USoundCue* MachineGun_A_Fire_2;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	USoundCue* MachineGun_A_Fire_3;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	USoundCue* MachineGun_A_Fire_4;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	USoundCue* MachineGun_A_Fire_5;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	USoundCue* MachineGun_A_Fire_6;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	USoundCue* MachineGun_A_Fire_7;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	USoundCue* MachineGun_A_Fire_8;

/* Misc */
public:
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	USoundCue* AmmoEmpty_1;

	/////// TODO: 나머지 추가
	////// 소프트 로딩
};
